name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 1:21
    - cron: '21 1 * * *'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version:
          - name: pypy2
            toxenv: pypy2-build
          - name: pypy2
            toxenv: pypy2-safety
          - name: pypy2
            toxenv: pypy2-tests
          - name: pypy3
            toxenv: pypy3-build
          - name: pypy3
            toxenv: pypy3-safety
          - name: pypy3
            toxenv: pypy3-tests
          - name: 3.6
            toxenv: py36-build
          - name: 3.6
            toxenv: py36-safety
          - name: 3.6
            toxenv: py36-tests
          - name: 3.7
            toxenv: py37-build
          - name: 3.7
            toxenv: py37-safety
          - name: 3.7
            toxenv: py37-tests
          - name: 3.8
            toxenv: py38-build
          - name: 3.8
            toxenv: py38-safety
          - name: 3.8
            toxenv: py38-tests
          - name: 3.8
            toxenv: readme
          - name: 3.8
            toxenv: secrets
          - name: 3.8
            toxenv: style
          - name: 3.8
            toxenv: docs-dirhtml
          - name: 3.8
            toxenv: docs-doctest
          - name: 3.8
            toxenv: docs-linkcheck
          - name: 3.8
            toxenv: docs-spelling
          - name: 3.8
            toxenv: docs-style

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version.name }}
    - name: Ensure we have new enough versions to respect python_version
      run: python -m pip install -U pip setuptools
    - name: Install dependencies
      run: sudo apt-get install -y libenchant-dev
      if: runner.os == 'Linux' && startsWith(matrix.python-version.toxenv, 'docs-')
    - name: Install dependencies
      run: brew install enchant
      if: runner.os == 'macOS' && startsWith(matrix.python-version.toxenv, 'docs-')
    - name: Install tox
      run: python -m pip install tox
    - name: Run tox
      run: python -m tox -e "${{ matrix.python-version.toxenv }}"
