name: Coverage

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install tox
      run: python -m pip install tox
    - name: Collect & Upload Coverage
      # codecov.io is too flaky to fail for this right now
      continue-on-error: true
      run: python -m tox -e py310-codecov
      env:
        CODECOV_TOKEN: a0be0b5c-a306-4507-a6b9-5c78741aaaab
